/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountHolderModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountHolderModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountHolderModel
        //private AccountHolderModel instance;

        public AccountHolderModelTests()
        {
            // TODO uncomment below to create an instance of AccountHolderModel
            //instance = new AccountHolderModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountHolderModel
        /// </summary>
        [Fact]
        public void AccountHolderModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountHolderModel
            //Assert.IsType<AccountHolderModel>(instance);
        }


        /// <summary>
        /// Test the property 'AccountReference'
        /// </summary>
        [Fact]
        public void AccountReferenceTest()
        {
            // TODO unit test for the property 'AccountReference'
        }
        /// <summary>
        /// Test the property 'FundCode'
        /// </summary>
        [Fact]
        public void FundCodeTest()
        {
            // TODO unit test for the property 'FundCode'
        }
        /// <summary>
        /// Test the property 'CurrentBalance'
        /// </summary>
        [Fact]
        public void CurrentBalanceTest()
        {
            // TODO unit test for the property 'CurrentBalance'
        }
        /// <summary>
        /// Test the property 'PeriodCredit'
        /// </summary>
        [Fact]
        public void PeriodCreditTest()
        {
            // TODO unit test for the property 'PeriodCredit'
        }
        /// <summary>
        /// Test the property 'PeriodDebit'
        /// </summary>
        [Fact]
        public void PeriodDebitTest()
        {
            // TODO unit test for the property 'PeriodDebit'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Forename'
        /// </summary>
        [Fact]
        public void ForenameTest()
        {
            // TODO unit test for the property 'Forename'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Fact]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'AddressLine3'
        /// </summary>
        [Fact]
        public void AddressLine3Test()
        {
            // TODO unit test for the property 'AddressLine3'
        }
        /// <summary>
        /// Test the property 'AddressLine4'
        /// </summary>
        [Fact]
        public void AddressLine4Test()
        {
            // TODO unit test for the property 'AddressLine4'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'RecordType'
        /// </summary>
        [Fact]
        public void RecordTypeTest()
        {
            // TODO unit test for the property 'RecordType'
        }
        /// <summary>
        /// Test the property 'UserField1'
        /// </summary>
        [Fact]
        public void UserField1Test()
        {
            // TODO unit test for the property 'UserField1'
        }
        /// <summary>
        /// Test the property 'UserField2'
        /// </summary>
        [Fact]
        public void UserField2Test()
        {
            // TODO unit test for the property 'UserField2'
        }
        /// <summary>
        /// Test the property 'UserField3'
        /// </summary>
        [Fact]
        public void UserField3Test()
        {
            // TODO unit test for the property 'UserField3'
        }
        /// <summary>
        /// Test the property 'PersonalisedStopMessage'
        /// </summary>
        [Fact]
        public void PersonalisedStopMessageTest()
        {
            // TODO unit test for the property 'PersonalisedStopMessage'
        }
        /// <summary>
        /// Test the property 'StopMessageReference'
        /// </summary>
        [Fact]
        public void StopMessageReferenceTest()
        {
            // TODO unit test for the property 'StopMessageReference'
        }

    }

}
