/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing FundMetadataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FundMetadataModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FundMetadataModel
        //private FundMetadataModel instance;

        public FundMetadataModelTests()
        {
            // TODO uncomment below to create an instance of FundMetadataModel
            //instance = new FundMetadataModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FundMetadataModel
        /// </summary>
        [Fact]
        public void FundMetadataModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" FundMetadataModel
            //Assert.IsType<FundMetadataModel>(instance);
        }


        /// <summary>
        /// Test the property 'FundCode'
        /// </summary>
        [Fact]
        public void FundCodeTest()
        {
            // TODO unit test for the property 'FundCode'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
