/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing FundModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FundModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FundModel
        //private FundModel instance;

        public FundModelTests()
        {
            // TODO uncomment below to create an instance of FundModel
            //instance = new FundModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FundModel
        /// </summary>
        [Fact]
        public void FundModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" FundModel
            //Assert.IsType<FundModel>(instance);
        }


        /// <summary>
        /// Test the property 'FundCode'
        /// </summary>
        [Fact]
        public void FundCodeTest()
        {
            // TODO unit test for the property 'FundCode'
        }
        /// <summary>
        /// Test the property 'FundName'
        /// </summary>
        [Fact]
        public void FundNameTest()
        {
            // TODO unit test for the property 'FundName'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
