/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MethodOfPaymentsSearchCriteriaModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MethodOfPaymentsSearchCriteriaModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MethodOfPaymentsSearchCriteriaModel
        //private MethodOfPaymentsSearchCriteriaModel instance;

        public MethodOfPaymentsSearchCriteriaModelTests()
        {
            // TODO uncomment below to create an instance of MethodOfPaymentsSearchCriteriaModel
            //instance = new MethodOfPaymentsSearchCriteriaModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MethodOfPaymentsSearchCriteriaModel
        /// </summary>
        [Fact]
        public void MethodOfPaymentsSearchCriteriaModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MethodOfPaymentsSearchCriteriaModel
            //Assert.IsType<MethodOfPaymentsSearchCriteriaModel>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
