/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MethodOfPaymentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MethodOfPaymentModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MethodOfPaymentModel
        //private MethodOfPaymentModel instance;

        public MethodOfPaymentModelTests()
        {
            // TODO uncomment below to create an instance of MethodOfPaymentModel
            //instance = new MethodOfPaymentModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MethodOfPaymentModel
        /// </summary>
        [Fact]
        public void MethodOfPaymentModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MethodOfPaymentModel
            //Assert.IsType<MethodOfPaymentModel>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MaximumAmount'
        /// </summary>
        [Fact]
        public void MaximumAmountTest()
        {
            // TODO unit test for the property 'MaximumAmount'
        }
        /// <summary>
        /// Test the property 'MinimumAmount'
        /// </summary>
        [Fact]
        public void MinimumAmountTest()
        {
            // TODO unit test for the property 'MinimumAmount'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

    }

}
