/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing NotificationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotificationModel
        //private NotificationModel instance;

        public NotificationModelTests()
        {
            // TODO uncomment below to create an instance of NotificationModel
            //instance = new NotificationModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationModel
        /// </summary>
        [Fact]
        public void NotificationModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotificationModel
            //Assert.IsType<NotificationModel>(instance);
        }


        /// <summary>
        /// Test the property 'MerchantReference'
        /// </summary>
        [Fact]
        public void MerchantReferenceTest()
        {
            // TODO unit test for the property 'MerchantReference'
        }
        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Fact]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'OriginalReference'
        /// </summary>
        [Fact]
        public void OriginalReferenceTest()
        {
            // TODO unit test for the property 'OriginalReference'
        }
        /// <summary>
        /// Test the property 'PspReference'
        /// </summary>
        [Fact]
        public void PspReferenceTest()
        {
            // TODO unit test for the property 'PspReference'
        }
        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Fact]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Fact]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }
        /// <summary>
        /// Test the property 'Live'
        /// </summary>
        [Fact]
        public void LiveTest()
        {
            // TODO unit test for the property 'Live'
        }
        /// <summary>
        /// Test the property 'Processed'
        /// </summary>
        [Fact]
        public void ProcessedTest()
        {
            // TODO unit test for the property 'Processed'
        }
        /// <summary>
        /// Test the property 'MerchantAccountCode'
        /// </summary>
        [Fact]
        public void MerchantAccountCodeTest()
        {
            // TODO unit test for the property 'MerchantAccountCode'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
