/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentModel
        //private PaymentModel instance;

        public PaymentModelTests()
        {
            // TODO uncomment below to create an instance of PaymentModel
            //instance = new PaymentModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentModel
        /// </summary>
        [Fact]
        public void PaymentModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentModel
            //Assert.IsType<PaymentModel>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Basket'
        /// </summary>
        [Fact]
        public void BasketTest()
        {
            // TODO unit test for the property 'Basket'
        }
        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Fact]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }
        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }
        /// <summary>
        /// Test the property 'FailUrl'
        /// </summary>
        [Fact]
        public void FailUrlTest()
        {
            // TODO unit test for the property 'FailUrl'
        }
        /// <summary>
        /// Test the property 'MopCode'
        /// </summary>
        [Fact]
        public void MopCodeTest()
        {
            // TODO unit test for the property 'MopCode'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }
        /// <summary>
        /// Test the property 'CallRecordingSource'
        /// </summary>
        [Fact]
        public void CallRecordingSourceTest()
        {
            // TODO unit test for the property 'CallRecordingSource'
        }
        /// <summary>
        /// Test the property 'CallRecordingUserName'
        /// </summary>
        [Fact]
        public void CallRecordingUserNameTest()
        {
            // TODO unit test for the property 'CallRecordingUserName'
        }

    }

}
