/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentModelAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentModelAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentModelAddress
        //private PaymentModelAddress instance;

        public PaymentModelAddressTests()
        {
            // TODO uncomment below to create an instance of PaymentModelAddress
            //instance = new PaymentModelAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentModelAddress
        /// </summary>
        [Fact]
        public void PaymentModelAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentModelAddress
            //Assert.IsType<PaymentModelAddress>(instance);
        }


        /// <summary>
        /// Test the property 'PayeeName'
        /// </summary>
        [Fact]
        public void PayeeNameTest()
        {
            // TODO unit test for the property 'PayeeName'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'AddressLine3'
        /// </summary>
        [Fact]
        public void AddressLine3Test()
        {
            // TODO unit test for the property 'AddressLine3'
        }
        /// <summary>
        /// Test the property 'AddressLine4'
        /// </summary>
        [Fact]
        public void AddressLine4Test()
        {
            // TODO unit test for the property 'AddressLine4'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }

    }

}
