/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentResponseModel
        //private PaymentResponseModel instance;

        public PaymentResponseModelTests()
        {
            // TODO uncomment below to create an instance of PaymentResponseModel
            //instance = new PaymentResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentResponseModel
        /// </summary>
        [Fact]
        public void PaymentResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentResponseModel
            //Assert.IsType<PaymentResponseModel>(instance);
        }


        /// <summary>
        /// Test the property 'PaymentUrl'
        /// </summary>
        [Fact]
        public void PaymentUrlTest()
        {
            // TODO unit test for the property 'PaymentUrl'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }

    }

}
