/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PendingTransactionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PendingTransactionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PendingTransactionModel
        //private PendingTransactionModel instance;

        public PendingTransactionModelTests()
        {
            // TODO uncomment below to create an instance of PendingTransactionModel
            //instance = new PendingTransactionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PendingTransactionModel
        /// </summary>
        [Fact]
        public void PendingTransactionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PendingTransactionModel
            //Assert.IsType<PendingTransactionModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'InternalReference'
        /// </summary>
        [Fact]
        public void InternalReferenceTest()
        {
            // TODO unit test for the property 'InternalReference'
        }
        /// <summary>
        /// Test the property 'OfficeCode'
        /// </summary>
        [Fact]
        public void OfficeCodeTest()
        {
            // TODO unit test for the property 'OfficeCode'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
        /// <summary>
        /// Test the property 'AccountReference'
        /// </summary>
        [Fact]
        public void AccountReferenceTest()
        {
            // TODO unit test for the property 'AccountReference'
        }
        /// <summary>
        /// Test the property 'UserCode'
        /// </summary>
        [Fact]
        public void UserCodeTest()
        {
            // TODO unit test for the property 'UserCode'
        }
        /// <summary>
        /// Test the property 'FundCode'
        /// </summary>
        [Fact]
        public void FundCodeTest()
        {
            // TODO unit test for the property 'FundCode'
        }
        /// <summary>
        /// Test the property 'MopCode'
        /// </summary>
        [Fact]
        public void MopCodeTest()
        {
            // TODO unit test for the property 'MopCode'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'VatCode'
        /// </summary>
        [Fact]
        public void VatCodeTest()
        {
            // TODO unit test for the property 'VatCode'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Fact]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }
        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }
        /// <summary>
        /// Test the property 'Narrative'
        /// </summary>
        [Fact]
        public void NarrativeTest()
        {
            // TODO unit test for the property 'Narrative'
        }
        /// <summary>
        /// Test the property 'BatchReference'
        /// </summary>
        [Fact]
        public void BatchReferenceTest()
        {
            // TODO unit test for the property 'BatchReference'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }
        /// <summary>
        /// Test the property 'PayeeName'
        /// </summary>
        [Fact]
        public void PayeeNameTest()
        {
            // TODO unit test for the property 'PayeeName'
        }
        /// <summary>
        /// Test the property 'PayeeBusinessName'
        /// </summary>
        [Fact]
        public void PayeeBusinessNameTest()
        {
            // TODO unit test for the property 'PayeeBusinessName'
        }
        /// <summary>
        /// Test the property 'PayeePremiseNumber'
        /// </summary>
        [Fact]
        public void PayeePremiseNumberTest()
        {
            // TODO unit test for the property 'PayeePremiseNumber'
        }
        /// <summary>
        /// Test the property 'PayeePremiseName'
        /// </summary>
        [Fact]
        public void PayeePremiseNameTest()
        {
            // TODO unit test for the property 'PayeePremiseName'
        }
        /// <summary>
        /// Test the property 'PayeeStreet'
        /// </summary>
        [Fact]
        public void PayeeStreetTest()
        {
            // TODO unit test for the property 'PayeeStreet'
        }
        /// <summary>
        /// Test the property 'PayeeArea'
        /// </summary>
        [Fact]
        public void PayeeAreaTest()
        {
            // TODO unit test for the property 'PayeeArea'
        }
        /// <summary>
        /// Test the property 'PayeeTown'
        /// </summary>
        [Fact]
        public void PayeeTownTest()
        {
            // TODO unit test for the property 'PayeeTown'
        }
        /// <summary>
        /// Test the property 'PayeeCounty'
        /// </summary>
        [Fact]
        public void PayeeCountyTest()
        {
            // TODO unit test for the property 'PayeeCounty'
        }
        /// <summary>
        /// Test the property 'PayeePostCode'
        /// </summary>
        [Fact]
        public void PayeePostCodeTest()
        {
            // TODO unit test for the property 'PayeePostCode'
        }
        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Fact]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }
        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }
        /// <summary>
        /// Test the property 'FailUrl'
        /// </summary>
        [Fact]
        public void FailUrlTest()
        {
            // TODO unit test for the property 'FailUrl'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }
        /// <summary>
        /// Test the property 'StatusId'
        /// </summary>
        [Fact]
        public void StatusIdTest()
        {
            // TODO unit test for the property 'StatusId'
        }

    }

}
