/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessedTransactionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessedTransactionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessedTransactionModel
        //private ProcessedTransactionModel instance;

        public ProcessedTransactionModelTests()
        {
            // TODO uncomment below to create an instance of ProcessedTransactionModel
            //instance = new ProcessedTransactionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessedTransactionModel
        /// </summary>
        [Fact]
        public void ProcessedTransactionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessedTransactionModel
            //Assert.IsType<ProcessedTransactionModel>(instance);
        }


        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'InternalReference'
        /// </summary>
        [Fact]
        public void InternalReferenceTest()
        {
            // TODO unit test for the property 'InternalReference'
        }
        /// <summary>
        /// Test the property 'PspReference'
        /// </summary>
        [Fact]
        public void PspReferenceTest()
        {
            // TODO unit test for the property 'PspReference'
        }
        /// <summary>
        /// Test the property 'OfficeCode'
        /// </summary>
        [Fact]
        public void OfficeCodeTest()
        {
            // TODO unit test for the property 'OfficeCode'
        }
        /// <summary>
        /// Test the property 'EntryDate'
        /// </summary>
        [Fact]
        public void EntryDateTest()
        {
            // TODO unit test for the property 'EntryDate'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
        /// <summary>
        /// Test the property 'AccountReference'
        /// </summary>
        [Fact]
        public void AccountReferenceTest()
        {
            // TODO unit test for the property 'AccountReference'
        }
        /// <summary>
        /// Test the property 'UserCode'
        /// </summary>
        [Fact]
        public void UserCodeTest()
        {
            // TODO unit test for the property 'UserCode'
        }
        /// <summary>
        /// Test the property 'FundCode'
        /// </summary>
        [Fact]
        public void FundCodeTest()
        {
            // TODO unit test for the property 'FundCode'
        }
        /// <summary>
        /// Test the property 'MopCode'
        /// </summary>
        [Fact]
        public void MopCodeTest()
        {
            // TODO unit test for the property 'MopCode'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'VatCode'
        /// </summary>
        [Fact]
        public void VatCodeTest()
        {
            // TODO unit test for the property 'VatCode'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Fact]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }
        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }
        /// <summary>
        /// Test the property 'Narrative'
        /// </summary>
        [Fact]
        public void NarrativeTest()
        {
            // TODO unit test for the property 'Narrative'
        }
        /// <summary>
        /// Test the property 'BatchReference'
        /// </summary>
        [Fact]
        public void BatchReferenceTest()
        {
            // TODO unit test for the property 'BatchReference'
        }

    }

}
