/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessFeeModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessFeeModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessFeeModel
        //private ProcessFeeModel instance;

        public ProcessFeeModelTests()
        {
            // TODO uncomment below to create an instance of ProcessFeeModel
            //instance = new ProcessFeeModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessFeeModel
        /// </summary>
        [Fact]
        public void ProcessFeeModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessFeeModel
            //Assert.IsType<ProcessFeeModel>(instance);
        }


        /// <summary>
        /// Test the property 'MerchantReference'
        /// </summary>
        [Fact]
        public void MerchantReferenceTest()
        {
            // TODO unit test for the property 'MerchantReference'
        }
        /// <summary>
        /// Test the property 'PspReference'
        /// </summary>
        [Fact]
        public void PspReferenceTest()
        {
            // TODO unit test for the property 'PspReference'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

    }

}
