/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessedTransactionsSearchCriteriaModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessedTransactionsSearchCriteriaModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessedTransactionsSearchCriteriaModel
        //private ProcessedTransactionsSearchCriteriaModel instance;

        public ProcessedTransactionsSearchCriteriaModelTests()
        {
            // TODO uncomment below to create an instance of ProcessedTransactionsSearchCriteriaModel
            //instance = new ProcessedTransactionsSearchCriteriaModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessedTransactionsSearchCriteriaModel
        /// </summary>
        [Fact]
        public void ProcessedTransactionsSearchCriteriaModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessedTransactionsSearchCriteriaModel
            //Assert.IsType<ProcessedTransactionsSearchCriteriaModel>(instance);
        }


        /// <summary>
        /// Test the property 'ReceiptNumber'
        /// </summary>
        [Fact]
        public void ReceiptNumberTest()
        {
            // TODO unit test for the property 'ReceiptNumber'
        }
        /// <summary>
        /// Test the property 'FundCodes'
        /// </summary>
        [Fact]
        public void FundCodesTest()
        {
            // TODO unit test for the property 'FundCodes'
        }
        /// <summary>
        /// Test the property 'AccountReference'
        /// </summary>
        [Fact]
        public void AccountReferenceTest()
        {
            // TODO unit test for the property 'AccountReference'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'AppReference'
        /// </summary>
        [Fact]
        public void AppReferenceTest()
        {
            // TODO unit test for the property 'AppReference'
        }
        /// <summary>
        /// Test the property 'MopCodes'
        /// </summary>
        [Fact]
        public void MopCodesTest()
        {
            // TODO unit test for the property 'MopCodes'
        }
        /// <summary>
        /// Test the property 'Narrative'
        /// </summary>
        [Fact]
        public void NarrativeTest()
        {
            // TODO unit test for the property 'Narrative'
        }
        /// <summary>
        /// Test the property 'InternalReference'
        /// </summary>
        [Fact]
        public void InternalReferenceTest()
        {
            // TODO unit test for the property 'InternalReference'
        }
        /// <summary>
        /// Test the property 'PspReference'
        /// </summary>
        [Fact]
        public void PspReferenceTest()
        {
            // TODO unit test for the property 'PspReference'
        }

    }

}
