/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessPaymentResponse
        //private ProcessPaymentResponse instance;

        public ProcessPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of ProcessPaymentResponse
            //instance = new ProcessPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessPaymentResponse
        /// </summary>
        [Fact]
        public void ProcessPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessPaymentResponse
            //Assert.IsType<ProcessPaymentResponse>(instance);
        }


        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'IsLegacy'
        /// </summary>
        [Fact]
        public void IsLegacyTest()
        {
            // TODO unit test for the property 'IsLegacy'
        }

    }

}
