/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SuspenseSearchCriteriaModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuspenseSearchCriteriaModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuspenseSearchCriteriaModel
        //private SuspenseSearchCriteriaModel instance;

        public SuspenseSearchCriteriaModelTests()
        {
            // TODO uncomment below to create an instance of SuspenseSearchCriteriaModel
            //instance = new SuspenseSearchCriteriaModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuspenseSearchCriteriaModel
        /// </summary>
        [Fact]
        public void SuspenseSearchCriteriaModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuspenseSearchCriteriaModel
            //Assert.IsType<SuspenseSearchCriteriaModel>(instance);
        }


        /// <summary>
        /// Test the property 'CreatedAtDateFrom'
        /// </summary>
        [Fact]
        public void CreatedAtDateFromTest()
        {
            // TODO unit test for the property 'CreatedAtDateFrom'
        }
        /// <summary>
        /// Test the property 'CreatedAtDateTo'
        /// </summary>
        [Fact]
        public void CreatedAtDateToTest()
        {
            // TODO unit test for the property 'CreatedAtDateTo'
        }

    }

}
