/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SuspenseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuspenseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuspenseModel
        //private SuspenseModel instance;

        public SuspenseModelTests()
        {
            // TODO uncomment below to create an instance of SuspenseModel
            //instance = new SuspenseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuspenseModel
        /// </summary>
        [Fact]
        public void SuspenseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuspenseModel
            //Assert.IsType<SuspenseModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'Narrative'
        /// </summary>
        [Fact]
        public void NarrativeTest()
        {
            // TODO unit test for the property 'Narrative'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ImportId'
        /// </summary>
        [Fact]
        public void ImportIdTest()
        {
            // TODO unit test for the property 'ImportId'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Fact]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
