/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LocalGovImsApiClient.Api;
using LocalGovImsApiClient.Model;
using LocalGovImsApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LocalGovImsApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionImportModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionImportModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionImportModel
        //private TransactionImportModel instance;

        public TransactionImportModelTests()
        {
            // TODO uncomment below to create an instance of TransactionImportModel
            //instance = new TransactionImportModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionImportModel
        /// </summary>
        [Fact]
        public void TransactionImportModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionImportModel
            //Assert.IsType<TransactionImportModel>(instance);
        }


        /// <summary>
        /// Test the property 'TransactionImportTypeId'
        /// </summary>
        [Fact]
        public void TransactionImportTypeIdTest()
        {
            // TODO unit test for the property 'TransactionImportTypeId'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'TotalNumberOfTransactions'
        /// </summary>
        [Fact]
        public void TotalNumberOfTransactionsTest()
        {
            // TODO unit test for the property 'TotalNumberOfTransactions'
        }
        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
