/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LocalGovImsApiClient.Client.OpenAPIDateConverter;

namespace LocalGovImsApiClient.Model
{
    /// <summary>
    /// SuspenseSearchCriteriaModel
    /// </summary>
    [DataContract(Name = "SuspenseSearchCriteriaModel")]
    public partial class SuspenseSearchCriteriaModel : IEquatable<SuspenseSearchCriteriaModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuspenseSearchCriteriaModel" /> class.
        /// </summary>
        /// <param name="createdAtDateFrom">createdAtDateFrom.</param>
        /// <param name="createdAtDateTo">createdAtDateTo.</param>
        public SuspenseSearchCriteriaModel(DateTime createdAtDateFrom = default(DateTime), DateTime createdAtDateTo = default(DateTime))
        {
            this.CreatedAtDateFrom = createdAtDateFrom;
            this.CreatedAtDateTo = createdAtDateTo;
        }

        /// <summary>
        /// Gets or Sets CreatedAtDateFrom
        /// </summary>
        [DataMember(Name = "CreatedAtDateFrom", EmitDefaultValue = false)]
        public DateTime CreatedAtDateFrom { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAtDateTo
        /// </summary>
        [DataMember(Name = "CreatedAtDateTo", EmitDefaultValue = false)]
        public DateTime CreatedAtDateTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuspenseSearchCriteriaModel {\n");
            sb.Append("  CreatedAtDateFrom: ").Append(CreatedAtDateFrom).Append("\n");
            sb.Append("  CreatedAtDateTo: ").Append(CreatedAtDateTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SuspenseSearchCriteriaModel);
        }

        /// <summary>
        /// Returns true if SuspenseSearchCriteriaModel instances are equal
        /// </summary>
        /// <param name="input">Instance of SuspenseSearchCriteriaModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SuspenseSearchCriteriaModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CreatedAtDateFrom == input.CreatedAtDateFrom ||
                    (this.CreatedAtDateFrom != null &&
                    this.CreatedAtDateFrom.Equals(input.CreatedAtDateFrom))
                ) && 
                (
                    this.CreatedAtDateTo == input.CreatedAtDateTo ||
                    (this.CreatedAtDateTo != null &&
                    this.CreatedAtDateTo.Equals(input.CreatedAtDateTo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CreatedAtDateFrom != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAtDateFrom.GetHashCode();
                }
                if (this.CreatedAtDateTo != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAtDateTo.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
