/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LocalGovImsApiClient.Client.OpenAPIDateConverter;

namespace LocalGovImsApiClient.Model
{
    /// <summary>
    /// TransactionImportModel
    /// </summary>
    [DataContract(Name = "TransactionImportModel")]
    public partial class TransactionImportModel : IEquatable<TransactionImportModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionImportModel" /> class.
        /// </summary>
        /// <param name="transactionImportTypeId">transactionImportTypeId.</param>
        /// <param name="externalReference">externalReference.</param>
        /// <param name="description">description.</param>
        /// <param name="totalAmount">totalAmount.</param>
        /// <param name="totalNumberOfTransactions">totalNumberOfTransactions.</param>
        /// <param name="rows">rows.</param>
        /// <param name="errors">errors.</param>
        public TransactionImportModel(int transactionImportTypeId = default(int), string externalReference = default(string), string description = default(string), double totalAmount = default(double), double totalNumberOfTransactions = default(double), List<ProcessedTransactionModel> rows = default(List<ProcessedTransactionModel>), List<string> errors = default(List<string>))
        {
            this.TransactionImportTypeId = transactionImportTypeId;
            this.ExternalReference = externalReference;
            this.Description = description;
            this.TotalAmount = totalAmount;
            this.TotalNumberOfTransactions = totalNumberOfTransactions;
            this.Rows = rows;
            this.Errors = errors;
        }

        /// <summary>
        /// Gets or Sets TransactionImportTypeId
        /// </summary>
        [DataMember(Name = "TransactionImportTypeId", EmitDefaultValue = false)]
        public int TransactionImportTypeId { get; set; }

        /// <summary>
        /// Gets or Sets ExternalReference
        /// </summary>
        [DataMember(Name = "ExternalReference", EmitDefaultValue = false)]
        public string ExternalReference { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [DataMember(Name = "TotalAmount", EmitDefaultValue = false)]
        public double TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets TotalNumberOfTransactions
        /// </summary>
        [DataMember(Name = "TotalNumberOfTransactions", EmitDefaultValue = false)]
        public double TotalNumberOfTransactions { get; set; }

        /// <summary>
        /// Gets or Sets Rows
        /// </summary>
        [DataMember(Name = "Rows", EmitDefaultValue = false)]
        public List<ProcessedTransactionModel> Rows { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "Errors", EmitDefaultValue = false)]
        public List<string> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionImportModel {\n");
            sb.Append("  TransactionImportTypeId: ").Append(TransactionImportTypeId).Append("\n");
            sb.Append("  ExternalReference: ").Append(ExternalReference).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  TotalNumberOfTransactions: ").Append(TotalNumberOfTransactions).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionImportModel);
        }

        /// <summary>
        /// Returns true if TransactionImportModel instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionImportModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionImportModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransactionImportTypeId == input.TransactionImportTypeId ||
                    this.TransactionImportTypeId.Equals(input.TransactionImportTypeId)
                ) && 
                (
                    this.ExternalReference == input.ExternalReference ||
                    (this.ExternalReference != null &&
                    this.ExternalReference.Equals(input.ExternalReference))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.TotalAmount == input.TotalAmount ||
                    this.TotalAmount.Equals(input.TotalAmount)
                ) && 
                (
                    this.TotalNumberOfTransactions == input.TotalNumberOfTransactions ||
                    this.TotalNumberOfTransactions.Equals(input.TotalNumberOfTransactions)
                ) && 
                (
                    this.Rows == input.Rows ||
                    this.Rows != null &&
                    input.Rows != null &&
                    this.Rows.SequenceEqual(input.Rows)
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.TransactionImportTypeId.GetHashCode();
                if (this.ExternalReference != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalReference.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TotalAmount.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalNumberOfTransactions.GetHashCode();
                if (this.Rows != null)
                {
                    hashCode = (hashCode * 59) + this.Rows.GetHashCode();
                }
                if (this.Errors != null)
                {
                    hashCode = (hashCode * 59) + this.Errors.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
