/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LocalGovImsApiClient.Client.OpenAPIDateConverter;

namespace LocalGovImsApiClient.Model
{
    /// <summary>
    /// UpdateCardDetailsModel
    /// </summary>
    [DataContract(Name = "UpdateCardDetailsModel")]
    public partial class UpdateCardDetailsModel : IEquatable<UpdateCardDetailsModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCardDetailsModel" /> class.
        /// </summary>
        /// <param name="merchantReference">merchantReference.</param>
        /// <param name="cardPrefix">cardPrefix.</param>
        /// <param name="cardSuffix">cardSuffix.</param>
        public UpdateCardDetailsModel(string merchantReference = default(string), string cardPrefix = default(string), string cardSuffix = default(string))
        {
            this.MerchantReference = merchantReference;
            this.CardPrefix = cardPrefix;
            this.CardSuffix = cardSuffix;
        }

        /// <summary>
        /// Gets or Sets MerchantReference
        /// </summary>
        [DataMember(Name = "MerchantReference", EmitDefaultValue = true)]
        public string MerchantReference { get; set; }

        /// <summary>
        /// Gets or Sets CardPrefix
        /// </summary>
        [DataMember(Name = "CardPrefix", EmitDefaultValue = true)]
        public string CardPrefix { get; set; }

        /// <summary>
        /// Gets or Sets CardSuffix
        /// </summary>
        [DataMember(Name = "CardSuffix", EmitDefaultValue = true)]
        public string CardSuffix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCardDetailsModel {\n");
            sb.Append("  MerchantReference: ").Append(MerchantReference).Append("\n");
            sb.Append("  CardPrefix: ").Append(CardPrefix).Append("\n");
            sb.Append("  CardSuffix: ").Append(CardSuffix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateCardDetailsModel);
        }

        /// <summary>
        /// Returns true if UpdateCardDetailsModel instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateCardDetailsModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCardDetailsModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MerchantReference == input.MerchantReference ||
                    (this.MerchantReference != null &&
                    this.MerchantReference.Equals(input.MerchantReference))
                ) && 
                (
                    this.CardPrefix == input.CardPrefix ||
                    (this.CardPrefix != null &&
                    this.CardPrefix.Equals(input.CardPrefix))
                ) && 
                (
                    this.CardSuffix == input.CardSuffix ||
                    (this.CardSuffix != null &&
                    this.CardSuffix.Equals(input.CardSuffix))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MerchantReference != null)
                {
                    hashCode = (hashCode * 59) + this.MerchantReference.GetHashCode();
                }
                if (this.CardPrefix != null)
                {
                    hashCode = (hashCode * 59) + this.CardPrefix.GetHashCode();
                }
                if (this.CardSuffix != null)
                {
                    hashCode = (hashCode * 59) + this.CardSuffix.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
