/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LocalGovImsApiClient.Client;
using LocalGovImsApiClient.Api;
// uncomment below to import models
//using LocalGovImsApiClient.Model;

namespace LocalGovImsApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing MethodOfPaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MethodOfPaymentsApiTests : IDisposable
    {
        private MethodOfPaymentsApi instance;

        public MethodOfPaymentsApiTests()
        {
            instance = new MethodOfPaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MethodOfPaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MethodOfPaymentsApi
            //Assert.IsType<MethodOfPaymentsApi>(instance);
        }

        /// <summary>
        /// Test MethodOfPaymentsSearch
        /// </summary>
        [Fact]
        public void MethodOfPaymentsSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string type = null;
            //var response = instance.MethodOfPaymentsSearch(type);
            //Assert.IsType<List<MethodOfPaymentModel>>(response);
        }
    }
}
