/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LocalGovImsApiClient.Client;
using LocalGovImsApiClient.Api;
// uncomment below to import models
//using LocalGovImsApiClient.Model;

namespace LocalGovImsApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing PendingTransactionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PendingTransactionsApiTests : IDisposable
    {
        private PendingTransactionsApi instance;

        public PendingTransactionsApiTests()
        {
            instance = new PendingTransactionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PendingTransactionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PendingTransactionsApi
            //Assert.IsType<PendingTransactionsApi>(instance);
        }

        /// <summary>
        /// Test PendingTransactionsAuthorise
        /// </summary>
        [Fact]
        public void PendingTransactionsAuthoriseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string reference = null;
            //AuthoriseModel authoriseModel = null;
            //instance.PendingTransactionsAuthorise(reference, authoriseModel);
        }

        /// <summary>
        /// Test PendingTransactionsGet
        /// </summary>
        [Fact]
        public void PendingTransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string reference = null;
            //var response = instance.PendingTransactionsGet(reference);
            //Assert.IsType<List<PendingTransactionModel>>(response);
        }

        /// <summary>
        /// Test PendingTransactionsPost
        /// </summary>
        [Fact]
        public void PendingTransactionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PendingTransactionModel pendingTransactionModel = null;
            //var response = instance.PendingTransactionsPost(pendingTransactionModel);
            //Assert.IsType<List<PendingTransactionModel>>(response);
        }

        /// <summary>
        /// Test PendingTransactionsProcessPayment
        /// </summary>
        [Fact]
        public void PendingTransactionsProcessPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string reference = null;
            //ProcessPaymentModel processPaymentModel = null;
            //var response = instance.PendingTransactionsProcessPayment(reference, processPaymentModel);
            //Assert.IsType<ProcessPaymentResponse>(response);
        }
    }
}
