/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LocalGovImsApiClient.Client;
using LocalGovImsApiClient.Api;
// uncomment below to import models
//using LocalGovImsApiClient.Model;

namespace LocalGovImsApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing ProcessedTransactionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProcessedTransactionsApiTests : IDisposable
    {
        private ProcessedTransactionsApi instance;

        public ProcessedTransactionsApiTests()
        {
            instance = new ProcessedTransactionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessedTransactionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProcessedTransactionsApi
            //Assert.IsType<ProcessedTransactionsApi>(instance);
        }

        /// <summary>
        /// Test ProcessedTransactionsGet
        /// </summary>
        [Fact]
        public void ProcessedTransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string reference = null;
            //var response = instance.ProcessedTransactionsGet(reference);
            //Assert.IsType<ProcessedTransactionModel>(response);
        }

        /// <summary>
        /// Test ProcessedTransactionsPost
        /// </summary>
        [Fact]
        public void ProcessedTransactionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessedTransactionModel processedTransactionModel = null;
            //var response = instance.ProcessedTransactionsPost(processedTransactionModel);
            //Assert.IsType<ProcessedTransactionModel>(response);
        }

        /// <summary>
        /// Test ProcessedTransactionsSearch
        /// </summary>
        [Fact]
        public void ProcessedTransactionsSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string receiptNumber = null;
            //List<string> fundCodes = null;
            //string accountReference = null;
            //decimal? amount = null;
            //DateTime? startDate = null;
            //DateTime? endDate = null;
            //string appReference = null;
            //List<string> mopCodes = null;
            //string narrative = null;
            //string internalReference = null;
            //string pspReference = null;
            //var response = instance.ProcessedTransactionsSearch(receiptNumber, fundCodes, accountReference, amount, startDate, endDate, appReference, mopCodes, narrative, internalReference, pspReference);
            //Assert.IsType<List<ProcessedTransactionModel>>(response);
        }

        /// <summary>
        /// Test ProcessedTransactionsUpdateCardDetails
        /// </summary>
        [Fact]
        public void ProcessedTransactionsUpdateCardDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string reference = null;
            //UpdateCardDetailsModel updateCardDetailsModel = null;
            //instance.ProcessedTransactionsUpdateCardDetails(reference, updateCardDetailsModel);
        }
    }
}
