/*
 * LocalGovImsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LocalGovImsApiClient.Client;
using LocalGovImsApiClient.Api;
// uncomment below to import models
//using LocalGovImsApiClient.Model;

namespace LocalGovImsApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing SuspenseApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SuspenseApiTests : IDisposable
    {
        private SuspenseApi instance;

        public SuspenseApiTests()
        {
            instance = new SuspenseApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuspenseApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SuspenseApi
            //Assert.IsType<SuspenseApi>(instance);
        }

        /// <summary>
        /// Test SuspenseGet
        /// </summary>
        [Fact]
        public void SuspenseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.SuspenseGet(id);
            //Assert.IsType<SuspenseModel>(response);
        }

        /// <summary>
        /// Test SuspensePost
        /// </summary>
        [Fact]
        public void SuspensePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SuspenseModel suspenseModel = null;
            //var response = instance.SuspensePost(suspenseModel);
            //Assert.IsType<SuspenseModel>(response);
        }

        /// <summary>
        /// Test SuspenseSearch
        /// </summary>
        [Fact]
        public void SuspenseSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? createdAtDateFrom = null;
            //DateTime? createdAtDateTo = null;
            //var response = instance.SuspenseSearch(createdAtDateFrom, createdAtDateTo);
            //Assert.IsType<List<SuspenseModel>>(response);
        }
    }
}
