/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LocalGovImsApiClient.Client;
using LocalGovImsApiClient.Api;
// uncomment below to import models
//using LocalGovImsApiClient.Model;

namespace LocalGovImsApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing TransactionImportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TransactionImportApiTests : IDisposable
    {
        private TransactionImportApi instance;

        public TransactionImportApiTests()
        {
            instance = new TransactionImportApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionImportApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TransactionImportApi
            //Assert.IsType<TransactionImportApi>(instance);
        }

        /// <summary>
        /// Test TransactionImportPost
        /// </summary>
        [Fact]
        public void TransactionImportPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TransactionImportModel model = null;
            //var response = instance.TransactionImportPost(model);
            //Assert.IsType<TransactionImportModel>(response);
        }
    }
}
